/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/home'
import { Route as ArticlesIndexImport } from './routes/articles/index'
import { Route as ArticlesIdImport } from './routes/articles/$id'

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesIndexRoute = ArticlesIndexImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesIdRoute = ArticlesIdImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdImport
      parentRoute: typeof rootRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles': typeof ArticlesIndexRoute
}

export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles': typeof ArticlesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/home': typeof HomeRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/': typeof ArticlesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/articles/$id' | '/articles'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/articles/$id' | '/articles'
  id: '__root__' | '/home' | '/articles/$id' | '/articles/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  ArticlesIdRoute: ArticlesIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/home",
        "/articles/$id",
        "/articles/"
      ]
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/articles/$id": {
      "filePath": "articles/$id.tsx"
    },
    "/articles/": {
      "filePath": "articles/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
